apiVersion: argoproj.io/v1alpha1  
kind: Application  
metadata:  
  name: javacicd 
  namespace: argocd  
spec:  
  project: default  
  source:  
    repoURL: https://github.com/Rajesh180118/Simple-Java-maven-CI-CD.git
    path: spring-boot-app-manifests  
    targetRevision: HEAD  
  destination:  
    server: https://kubernetes.default.svc  
    namespace: default  
  syncPolicy:  
    automated: {}  
